line-length = 80
target-version = "py312"

# Linter config
[lint]

select = ["UP", "F", "I"]
ignore = ["E741", "UP017"]

# Enable preview rules
preview = true

[isort]
force-single-line = true

# Format config
[format]

# Enable preview rules
preview = true
